{{- range .Values.domain }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ . | replace "." "-" }}
  namespace: istio-system
spec:
  duration: 2160h # 90d
  renewBefore: 2148h
  secretName: {{ . | replace "." "-" }}
  commonName: {{ . }}
  dnsNames:
    - {{ . }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
{{- end }}